### ISSUE TITLE
no "update connection" button

### ISSUE THREAD

**Issue by aejolene** [matrix-msu/kora-connect#2] opened 2016-08-03 23:01 UTC
Hello @seilagonzalez ! I've successfully installed the plugin via FTP on a WordPress site hosted at MSU/Matrix. On the Connect screen,  there's no "update connection" button and nothing happens when I press enter after entering the KORA installation URL.

Screenshot is here [https://drive.google.com/file/d/0B2CIBbm8KbxDVkZJSm13aDBzcUU2M1RFWnZka0N6bFFUZVRj/view?usp=sharing](https://drive.google.com/file/d/0B2CIBbm8KbxDVkZJSm13aDBzcUU2M1RFWnZka0N6bFFUZVRj/view?usp=sharing)

**Comment by seilagonzalez** [comment] 2016-08-04 13:34
Hi did you setup the config file? There is a dbConfig.dist ... you need to setup that config file and save as dbConfig.php. Let me know if that's not the problem. Thanks

**Comment by aejolene** [comment] 2016-08-04 13:40
I did that, but maybe there's a chance I messed it up along the way. I'm
going to try to start from scratch and see if I reproduce the issue.

**Comment by watrall** [comment] 2016-08-04 13:42
do you have the info proper info/credentials for the MATRIX KORA install (where your project is)?

**Comment by aejolene** [comment] 2016-08-04 13:44
@watrall I haven't gotten that far yet, but I may be missing token information. The Project Name and SID display on my projects page, but I can't find anything about a token.

**Comment by watrall** [comment] 2016-08-04 13:48
https://github.com/matrix-msu/kora-connect/wiki/2.-Connect

You actually need to go into your KORA project to get the PID, the token, and the SID

**Comment by aejolene** [comment] 2016-08-04 13:54
Back to the dbconfig file, do I just need to edit credentials for kordat_dbuser and kordat_dbpass as indicated in the instructions, or do I also need to edit the others (kordat_dbhostname, kordat_dbhostuser, kordat_dbselectname, kordat_dbhostpass)? If I need to edit them all, are the dbhost values the WP login credentials? What belongs in dbselectname?

**Comment by aejolene** [comment] 2016-08-04 13:58
Here's another place that might be a hitch-

From the wiki: 

> For security purposes, open the files kora_database_admin.php and kora_execute.php and change the passwords listed there. The password must be changed twice in the database_admin file and once in the execute file. Make sure that all three passwords match exactly.

I don't see any XXXX password values in kora_database_admin.php and I'm not able to find the kora_execute.php file at all.

**Comment by aejolene** [comment] 2016-08-06 20:07
Hi all,

Here's where I am currently. I cloned this repository to my machine. I FTPd the plugin files to /matrix/www/vaarchaeology/public_html/wp-content/plugins

I located dbconfig.php.dist and edited only the first two entries, as specified on the wiki

```
<?php
    //Server Authentication Settings
    //server username
    define("kordat_dbuser", "");
    //^I put my KORA login here
        //server password
    define("kordat_dbpass", "");
        ////^I put my KORA password here
    // User Database Settings
    //hostname
    define("kordat_dbhostname", "XXXXXX");
    //db username
    define("kordat_dbhostuser","XXXXX");
    //db name
    define("kordat_dbselectname","XXXX");
    //db password
    define("kordat_dbhostpass","XXXXXX");

    define("kora_url","XXXXX");

?>
```

Then I saved the file as dbconfig.php and FTPd it over to the WP site.

Following the Configure KORA-Connect instructions on the wiki, I was not able to locate an editable password field in kora_database_admin.php nor was I able to locate kora_execute.php at all.

I activated the plugin in WP and again saw the same results above. https://drive.google.com/file/d/0B2CIBbm8KbxDVkZJSm13aDBzcUU2M1RFWnZka0N6bFFUZVRj/view?usp=sharing 

Simple question- do I need to be replacing all of the passwords with XXXX placeholders? If that's the problem, maybe I'm confusing which credentials go where. Thank you!

**Comment by seilagonzalez** [comment] 2016-08-08 12:18
you need to include all the entries... included the db info for kora.

**Comment by watrall** [comment] 2016-08-08 12:21
@aejolene - since you are using a MATRIX KORA install, we can provide the credentials to you separately.  Normally, you'd have these credentials if you were hosting KORA on your own server

**Comment by watrall** [comment] 2016-08-09 17:59
@aejolene - we figured out the issue.  The build on GitHub wasn't the most recent one - it was missing a bunch of libraries.  We'll push the new version tomorrow morning.  Hopefully, that will resolve the issue you are having

**Comment by aejolene** [comment] 2016-08-09 18:03
@watrall Thanks for the update. I'll clear my schedule and eagerly await.

**Comment by watrall** [comment] 2016-08-10 13:34
@aejolene - Plugin has been totally updated.  Please totally delete the version you have, install the current version, and configure with credentials.  Should work.  Let us know here and I'll either close this issue or we'll continue to troubleshoot

**Comment by aejolene** [comment] 2016-08-10 13:36
Awesome. I should have an update within an hour or so. Thanks all.

**Comment by aejolene** [comment] 2016-08-10 14:35
Hi all. Unfortunately I'm having the same problem. I cloned the repository, updated the dbconfig.php file, and FTP'd it over. After I activate the plugin, I'm still seeing the same dashboard screen with no ability to connect.

**Comment by watrall** [comment] 2016-08-10 15:09
@aejolene - I can confirm that @seilagonzalez has a fully functional version running on a sandbox WP install on one of our dev servers.  Did you deactivate the plugin, totally delete it, and then re-install?

**Comment by aejolene** [comment] 2016-08-10 15:16
I did. Here's my workflow that I'm going to try again:

Deactivate existing plugin in WP
Delete the directory via FileZilla
Re-upload the new directory via FileZilla
Activate Plugin

FYI- I still wasn't able to follow this part of the Wiki install
instructions:
//For security purposes, open the files kora_database_admin.php and
kora_execute.php and change the passwords listed there. The password must
be changed twice in the database_admin file and once in the execute file.
Make sure that all three passwords match exactly//

There's no apparent password value to change in kora_database_admin.php and
I still don't see kora_execute.php at all. That may not have any relevance,
but I'm including it just in case.

Could it have something to do with how I'm uploading the files?

**Comment by watrall** [comment] 2016-08-11 00:34
so, the primary issue is that, somewhere in the plugin code, it is jsut called “kora,” while its called “kora connect” on github…and if you upload the “kora connect” folder the /plugins in wp and then activate the plugin, WP has a nervous breakdown and breaks.  So, @seilagonzalez went into your install and fixed things.  She has also tested it out and made sure it works.  The one thing is that you will need to go into the config file and replace the credentials with your own (the ones in there now were for the purpose of testing)

**Comment by aejolene** [comment] 2016-08-11 00:39
Joy!!! Thank you so much, @watrall and @seilagonzalez , for helping me through this. I will test as soon as I possibly can.

When I change the credentials in the config file, does that mean I should delete first (copying files, of course) and then reinstall? Or will just replacing the config file with my own do the trick?

**Comment by watrall** [comment] 2016-08-11 00:41
I'd deactivate first...then you can just edit the config file and put your credentials in (or upload a new version of the config file with your credentials).  Then reactivate.  @seilagonzalez - what do you think?

**Comment by aejolene** [comment] 2016-08-11 15:10
Success!!! I'm in, fully connected, and building galleries. Thanks again.

**Comment by aejolene** [comment] 2016-08-11 15:32
@watrall Going forward, what is the best mechanism for questions/help? A separate Help Wanted issue here? An email? For example, I created a gallery, but there don't appear to be pages for the individual objects. Do I manually make each of them? I'm also not quite sure how to use the library.

**Comment by watrall** [comment] 2016-08-11 15:35
Wonderful!  I'm going to close this issue down.  @aejolene - open another issue.  Use "help wanted" or "question" label.

**Closed as completed by watrall** 2016-08-11 15:35 UTC
Labels: bug, help wanted
